### ISSUE TITLE
Create new app. Clean-up on mandatory fields clean-up and grammar/spelling

### ISSUE THREAD

**Issue by nathanwatkinstemplar** [Templar-Payments/Templar_Payments_BugTracking#74] opened 2021-07-23 09:31 UTC
https://share.vidyard.com/watch/X9v9CSyK6XsbJzPpymkPPt?

- When you click upload and then the name of the document pop up, this has underscores within the document text that need removing
- Where it says 'Nathan Watkins Passport' can we change Passport to  'Proof of ID'

**Comment by WilliamTemplar** [comment] 2021-07-23 15:04
Found the cause of the issue. Since it's on the backend, Dan will push the fix when he gets time

**Comment by WilliamTemplar** [comment] 2021-07-23 15:33
Underscores are removed on the Front end, waiting on PR

**Comment by WilliamTemplar** [comment] 2021-07-23 18:15
@NathanLeadill replace line 229 on applicationController on BE with this
<img width="871" alt="Screenshot 2021-07-23 at 19 13 04" src="https://user-images.githubusercontent.com/83643714/126824104-35ad727e-4a46-45cd-8013-802b40a81c45.png">

**Comment by NathanLeadill** [comment] 2021-07-23 19:35
I've done this merged in

**Closed as completed by NathanLeadill** 2021-07-23 19:35 UTC
